clear all; clc; close all;

y_pred = getEVModelOneDay([pwd,'\','shortTermEVData.csv'],...
                                                 [pwd,'\','forecastEVData.csv'],...
                                                 [pwd,'\','resultEVData.csv'])